architectury {
	platformSetupLoomIde()
	fabric()
}

configurations {
	common
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentFabric.extendsFrom common
}

dependencies {
	implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
	api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
	api "dev.architectury:architectury-fabric:${rootProject.architectury_version}"
	compileOnly "com.terraformersmc:modmenu:${rootProject.mod_menu_version}"
	common(project(path: ':common', configuration: 'apiElements')) { transitive = false }
	shadowCommon(project(path: ':common', configuration: 'transformProductionFabric')) { transitive = false }
}
