org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.parallel=true
# mod properties
mod_version=3.3.2
maven_group=mtr
# dependencies
minecraft_mod_api_tools_version=b33012bd4098a807dca91dc469f2b0018df6ff96
minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.159.0+26.2
neoforge_version=26.2.0.75
architectury_version=21.0.7
mod_menu_version=19.0.0-alpha.1
