org.gradle.jvmargs=-Xmx6G -Dfile.encoding=GBK -Dconsole.encoding=GBK
org.gradle.parallel=true
# mod properties
mod_version=1.0.0
# Loader dependency version preserves existing MTR addon version constraints.
mtr_compat_version=1.21.1-3.3.9
archives_base_name=YanlingMTR
minecraft_version=1.21.1
maven_group=mtr
# dependencies
minecraft_mod_api_tools_version=b33012bd4098a807dca91dc469f2b0018df6ff96
