plugins {
	id "java"
	id "architectury-plugin" version "3.4.164"
	id "dev.architectury.loom" version "1.11.458"
	id "com.gradleup.shadow" version "8.3.0"
}

apply from: rootProject.file("gradle/platform.gradle")

project.architectury {
	platformSetupLoomIde()
	fabric()
}

dependencies {
	modImplementation "net.fabricmc:fabric-loader:0.19.3"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.116.15+1.21.1"
	modImplementation "dev.architectury:architectury-fabric:13.0.11"
	modCompileOnly files(rootProject.mtrProject.toPath().resolve("build/release/MTR-fabric-1.21.1-3.3.0-beta-1.jar").toFile())

	implementation project(":common")
}

remapJar {
	archiveClassifier.set("")
}
