modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "mtr"
version = "${version}"
displayName = "YanlingMTR"
authors = "linlunaire, Jonathan Ho, MTR contributors"
description = "YanlingMTR: automated railways for Minecraft. An independent community fork of Minecraft Transit Railway."
logoFile = "icon.png"

[[dependencies.mtr]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"
